[2023-08-17T00:11:56.313+0300] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dag_data_lake.extract_data_stackoverflow scheduled__2023-08-15T18:00:00+00:00 [queued]>
[2023-08-17T00:11:56.367+0300] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dag_data_lake.extract_data_stackoverflow scheduled__2023-08-15T18:00:00+00:00 [queued]>
[2023-08-17T00:11:56.368+0300] {taskinstance.py:1308} INFO - Starting attempt 1 of 3
[2023-08-17T00:11:56.481+0300] {taskinstance.py:1327} INFO - Executing <Task(SimpleHttpOperator): extract_data_stackoverflow> on 2023-08-15 18:00:00+00:00
[2023-08-17T00:11:56.510+0300] {standard_task_runner.py:57} INFO - Started process 235125 to run task
[2023-08-17T00:11:56.574+0300] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'dag_data_lake', 'extract_data_stackoverflow', 'scheduled__2023-08-15T18:00:00+00:00', '--job-id', '7', '--raw', '--subdir', 'DAGS_FOLDER/main.py', '--cfg-path', '/tmp/tmpjs4hxe6o']
[2023-08-17T00:11:56.578+0300] {standard_task_runner.py:85} INFO - Job 7: Subtask extract_data_stackoverflow
[2023-08-17T00:11:57.512+0300] {task_command.py:410} INFO - Running <TaskInstance: dag_data_lake.extract_data_stackoverflow scheduled__2023-08-15T18:00:00+00:00 [running]> on host std21006
[2023-08-17T00:12:00.577+0300] {taskinstance.py:1545} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='hei.nalisoa@gmail.com,hei.tsirimaholy@gmail.com' AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='dag_data_lake' AIRFLOW_CTX_TASK_ID='extract_data_stackoverflow' AIRFLOW_CTX_EXECUTION_DATE='2023-08-15T18:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-08-15T18:00:00+00:00'
[2023-08-17T00:12:00.593+0300] {http.py:143} INFO - Calling HTTP method
[2023-08-17T00:12:01.309+0300] {taskinstance.py:1824} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/ylan/airflow/venv/lib/python3.9/site-packages/airflow/providers/http/operators/http.py", line 145, in execute
    response = http.run(self.endpoint, self.data, self.headers, self.extra_options)
  File "/home/ylan/airflow/venv/lib/python3.9/site-packages/airflow/providers/http/hooks/http.py", line 145, in run
    session = self.get_conn(headers)
  File "/home/ylan/airflow/venv/lib/python3.9/site-packages/airflow/providers/http/hooks/http.py", line 98, in get_conn
    conn = self.get_connection(self.http_conn_id)
  File "/home/ylan/airflow/venv/lib/python3.9/site-packages/airflow/hooks/base.py", line 72, in get_connection
    conn = Connection.get_connection_from_secrets(conn_id)
  File "/home/ylan/airflow/venv/lib/python3.9/site-packages/airflow/models/connection.py", line 463, in get_connection_from_secrets
    raise AirflowNotFoundException(f"The conn_id `{conn_id}` isn't defined")
airflow.exceptions.AirflowNotFoundException: The conn_id `api` isn't defined
[2023-08-17T00:12:01.334+0300] {taskinstance.py:1345} INFO - Marking task as UP_FOR_RETRY. dag_id=dag_data_lake, task_id=extract_data_stackoverflow, execution_date=20230815T180000, start_date=20230816T211156, end_date=20230816T211201
[2023-08-17T00:12:01.436+0300] {standard_task_runner.py:104} ERROR - Failed to execute job 7 for task extract_data_stackoverflow (The conn_id `api` isn't defined; 235125)
[2023-08-17T00:12:01.521+0300] {local_task_job_runner.py:225} INFO - Task exited with return code 1
[2023-08-17T00:12:01.883+0300] {taskinstance.py:2653} INFO - 0 downstream tasks scheduled from follow-on schedule check
